In [7]:
data_dict = {
    
    
}

In [8]:
base_dir = "./Data_images"

In [9]:
import os
import requests
from PIL import Image
from io import BytesIO

# Hàm tải và lưu ảnh
def tai_va_luu_anh(url, path_to_save):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            img = Image.open(BytesIO(response.content))

            # Kiểm tra nếu ảnh là trong chế độ RGBA, chuyển nó sang RGB
            if img.mode == 'RGBA':
                img = img.convert('RGB')

            img.save(path_to_save)
            print(f"Đã lưu: {path_to_save}")
        else:
            print(f"Lỗi khi tải ảnh từ {url}: Status code {response.status_code}")
    except Exception as e:
        print(f"Không thể tải ảnh từ {url}. Lỗi: {e}")

# Giả sử `base_dir` và `data_dict` đã được định nghĩa
# Duyệt qua từ điển và tải ảnh
for label, urls in data_dict.items():
    # Tạo thư mục cho mỗi label nếu chưa tồn tại
    label_dir = os.path.join(base_dir, label)  # Sử dụng trực tiếp tên label
    os.makedirs(label_dir, exist_ok=True)
    
    # Tải và lưu mỗi ảnh trong list
    for i, url in enumerate(urls):
        file_name = f"anh_{i}.jpg"  # Đặt tên file
        path_to_save = os.path.join(label_dir, file_name)
        tai_va_luu_anh(url, path_to_save)

In [10]:
import glob
import numpy as np
import os
from PIL import Image

    
def doc_va_chuyen_doi_anh_voi_nhan(thu_muc, label, target_size=(128, 128)):
    data_arrays = []
    labels = []
    
    # Include both JPG and PNG files in the search pattern
    for file_path in glob.glob(os.path.join(thu_muc, "*.*")):
        if file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
            img = Image.open(file_path).convert('RGB')  # Convert to RGB
            img_resized = img.resize(target_size)
            img_array = np.array(img_resized) / 255.0
            #print(img_array.shape)  # Debugging to check shape
            data_arrays.append(img_array)
            labels.append(label)
    
    return np.array(data_arrays), np.array(labels)

data_train = []
labels_train = []
data_test = []
labels_test = []

# Sử dụng hàm cho mỗi thư mục nhãn
for label in os.listdir(base_dir):
    full_path = os.path.join(base_dir, label)
    print(full_path)
    data, labels = doc_va_chuyen_doi_anh_voi_nhan(full_path, label)
    
    # Giả sử chia 90% đầu làm dữ liệu huấn luyện và 10% còn lại làm dữ liệu kiểm tra
    split_idx = int(len(data) * 0.9)
    data_train.extend(data[:split_idx])
    labels_train.extend(labels[:split_idx])
    
    data_test.extend(data[split_idx:])
    labels_test.extend(labels[split_idx:])

# Chuyển các list thành numpy arrays
data_train = np.array(data_train)
labels_train = np.array(labels_train)
data_test = np.array(data_test)
labels_test = np.array(labels_test)

print(f"Dữ liệu huấn luyện: {data_train.shape}, Nhãn huấn luyện: {labels_train.shape}")
print(f"Dữ liệu kiểm tra: {data_test.shape}, Nhãn kiểm tra: {labels_test.shape}")


./Data_images\Iphone 11
./Data_images\Iphone 13
./Data_images\Iphone 13 Pro
./Data_images\Iphone 14
./Data_images\Iphone 14 Pro
./Data_images\Iphone 15
./Data_images\Iphone 15 Pro
./Data_images\Oppo Reno11 F
./Data_images\Samsung Galaxy M34
./Data_images\Samsung Galaxy S23
./Data_images\Samsung Galaxy S23 Ultra
./Data_images\Samsung Galaxy Z Fold5
./Data_images\Samsung Galaxy Z Fold6
./Data_images\Tcl Google Tv
./Data_images\Xiaomi Poco X6 Pro
./Data_images\Xiaomi Redmi Note 13
Dữ liệu huấn luyện: (951, 128, 128, 3), Nhãn huấn luyện: (951,)
Dữ liệu kiểm tra: (115, 128, 128, 3), Nhãn kiểm tra: (115,)


In [11]:
data_test.shape

(115, 128, 128, 3)

In [12]:
labels_test

array(['Iphone 11', 'Iphone 11', 'Iphone 11', 'Iphone 11', 'Iphone 11',
       'Iphone 11', 'Iphone 11', 'Iphone 11', 'Iphone 11', 'Iphone 11',
       'Iphone 13', 'Iphone 13', 'Iphone 13', 'Iphone 13', 'Iphone 13',
       'Iphone 13', 'Iphone 13', 'Iphone 13 Pro', 'Iphone 13 Pro',
       'Iphone 13 Pro', 'Iphone 13 Pro', 'Iphone 13 Pro', 'Iphone 13 Pro',
       'Iphone 13 Pro', 'Iphone 13 Pro', 'Iphone 14', 'Iphone 14',
       'Iphone 14', 'Iphone 14', 'Iphone 14', 'Iphone 14', 'Iphone 14',
       'Iphone 14 Pro', 'Iphone 14 Pro', 'Iphone 14 Pro', 'Iphone 14 Pro',
       'Iphone 14 Pro', 'Iphone 14 Pro', 'Iphone 14 Pro', 'Iphone 14 Pro',
       'Iphone 15', 'Iphone 15', 'Iphone 15', 'Iphone 15', 'Iphone 15',
       'Iphone 15', 'Iphone 15 Pro', 'Iphone 15 Pro', 'Iphone 15 Pro',
       'Iphone 15 Pro', 'Iphone 15 Pro', 'Iphone 15 Pro', 'Iphone 15 Pro',
       'Iphone 15 Pro', 'Iphone 15 Pro', 'Iphone 15 Pro', 'Oppo Reno11 F',
       'Oppo Reno11 F', 'Oppo Reno11 F', 'Oppo Reno11 F', 'O

In [13]:
from sklearn.preprocessing import LabelEncoder

# Tạo một encoder
encoder = LabelEncoder()

# Đưa nhãn văn bản về dạng số nguyên
labels_train_encoded = encoder.fit_transform(labels_train)
labels_test_encoded = encoder.fit_transform(labels_test)
# In nhãn sau khi được mã hóa để kiểm tra
print(labels_train_encoded)
print(labels_test_encoded)

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4

In [14]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [15]:
from tensorflow.keras.utils import to_categorical


# Chuyển đổi nhãn sang dạng one-hot
labels_train_one_hot = to_categorical(labels_train_encoded)
labels_test_one_hot = to_categorical(labels_test_encoded)

In [16]:
labels_train_one_hot

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [17]:
entries = os.listdir(base_dir)
folder_count = sum(os.path.isdir(os.path.join(base_dir, entry)) for entry in entries)
print(folder_count)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input

model = Sequential([
    Input(shape=(128, 128, 3)),  # Sử dụng Input layer để xác định kích thước đầu vào
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(folder_count, activation='softmax')  # `len(data_dict)` là số lớp
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

16


In [18]:
import tensorflow as tf

# train_dataset = tf.data.Dataset.from_tensor_slices((data_train, labels_train_one_hot)).batch(32).repeat()
# test_dataset = tf.data.Dataset.from_tensor_slices((data_test, labels_test_one_hot)).batch(32).repeat()

# Huấn luyện mô hình validation_data=(data_test, labels_test_one_hot)
history = model.fit(
    data_train, labels_train_one_hot,
    epochs=11, # Số lượng bước huấn luyện mỗi epoch
)

Epoch 1/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 19s 472ms/step - accuracy: 0.0816 - loss: 3.3648
Epoch 2/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 14s 463ms/step - accuracy: 0.1293 - loss: 2.6876
Epoch 3/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 12s 413ms/step - accuracy: 0.2311 - loss: 2.4575
Epoch 4/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 12s 414ms/step - accuracy: 0.3488 - loss: 2.1349
Epoch 5/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 13s 433ms/step - accuracy: 0.5014 - loss: 1.5319
Epoch 6/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 13s 415ms/step - accuracy: 0.6903 - loss: 1.0467
Epoch 7/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 13s 419ms/step - accuracy: 0.7637 - loss: 0.7921
Epoch 8/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 13s 437ms/step - accuracy: 0.8511 - loss: 0.4984
Epoch 9/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 13s 422ms/step - accuracy: 0.9027 - loss: 0.3667
Epoch 10/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 13s 433ms/step - accuracy: 0.9172 - loss: 0.2951
Epoch 11/11
30/30 ━━━━━━━━━━━━━━━━━━━━ 13s 444ms/step - accuracy: 0.9440 - loss: 0.2178


In [19]:
model.metrics_names

['loss', 'compile_metrics']

In [20]:
model.evaluate(data_test,labels_test_one_hot)

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 210ms/step - accuracy: 0.3315 - loss: 3.8739


[3.881770133972168, 0.365217387676239]

In [21]:
from sklearn.metrics import classification_report
import numpy as np

predictions = model.predict(data_test)

predicted_classes = np.argmax(predictions, axis=1)

actual_classes = np.argmax(labels_test_one_hot, axis=1)

report = classification_report(actual_classes, predicted_classes)
print(report)

4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 378ms/step
              precision    recall  f1-score   support

           0       0.38      0.30      0.33        10
           1       0.25      0.29      0.27         7
           2       0.29      0.25      0.27         8
           3       0.75      0.43      0.55         7
           4       0.36      0.50      0.42         8
           5       0.50      0.33      0.40         6
           6       0.30      0.30      0.30        10
           7       0.50      0.12      0.20         8
           8       0.33      0.20      0.25         5
           9       0.33      0.20      0.25         5
          10       0.25      0.40      0.31         5
          11       0.15      0.22      0.18         9
          12       0.29      0.33      0.31         6
          13       0.83      0.83      0.83         6
          14       0.25      0.50      0.33         6
          15       0.67      0.67      0.67         9

    accuracy                           0.

In [22]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Giả sử predicted_classes là nhãn dự đoán từ mô hình của bạn
# và actual_classes là nhãn thực tế của tập kiểm tra
 # [[41  7  1  0  2]
 # [ 1  3  1  3  3]
 # [ 8  0 34  1  8]
 # [ 7  1  1 15  5]
 # [ 4  0  7  7 32]]
# Tính ma trận nhầm lẫn
cm = confusion_matrix(actual_classes, predicted_classes)

# In ma trận nhầm lẫn
print(cm)

# Tính TP, TN, FP, FN cho mỗi lớp
TP = np.diag(cm)
FP = cm.sum(axis=0) - np.diag(cm)
FN = cm.sum(axis=1) - np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# In ra số lượng TP, TN, FP, FN cho mỗi lớp
print("True Positives: ", TP)
print("False Positives: ", FP)
print("True Negatives: ", TN)
print("False Negatives: ", FN)


[[3 3 0 0 0 0 0 0 1 0 1 0 0 0 2 0]
 [0 2 1 0 1 1 1 0 0 0 1 0 0 0 0 0]
 [1 0 2 0 0 0 1 0 0 0 0 2 0 1 1 0]
 [0 1 0 3 0 1 0 0 0 0 0 0 1 0 1 0]
 [0 0 1 0 4 0 0 0 0 0 0 1 0 0 1 1]
 [1 1 0 0 0 2 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 3 0 0 0 0 1 0 0 2 1]
 [0 0 0 1 2 0 1 1 1 0 0 0 1 0 0 1]
 [0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 2 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 2 1 0 0 0 0]
 [1 0 1 0 0 0 0 1 0 0 1 2 2 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 2 2 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 5 0 0]
 [0 0 2 0 0 0 1 0 0 0 0 0 0 0 3 0]
 [1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 6]]
True Positives:  [3 2 2 3 4 2 3 1 1 1 2 2 2 5 3 6]
False Positives:  [ 5  6  5  1  7  2  7  1  2  2  6 11  5  1  9  3]
True Negatives:  [100 102 102 107 100 107  98 106 108 108 104  95 104 108 100 103]
False Negatives:  [7 5 6 4 4 4 7 7 4 4 3 7 4 1 3 3]


In [23]:
model.save('e-commerce-model.keras')

In [24]:
import joblib

# Lưu encoder
joblib.dump(encoder, 'label_encoder.pkl')

['label_encoder.pkl']

In [25]:
# run this cell
import requests
import numpy as np
from keras.preprocessing import image
from keras.models import load_model
import joblib

url = 'http://localhost:3000/Imgsearch'

# Tải LabelEncoder
encoder = joblib.load('label_encoder.pkl')

# Chuẩn bị ảnh
img_path = './uploads/test1.jpg'
img = image.load_img(img_path, target_size=(128, 128))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.0

# Dự đoán
predictions = model.predict(img_array)

# Lấy tất cả nhãn từ encoder
all_labels = encoder.classes_

# Hiển thị xác suất dự đoán cho mỗi nhãn
print("Xác suất dự đoán cho mỗi nhãn:")
for label, prob in zip(all_labels, predictions[0]):
        if prob * 100 > 0:  # 
            print(f"{label}: {prob*100:.2f}%")
    


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Xác suất dự đoán cho mỗi nhãn:
Iphone 11: 0.00%
Iphone 13: 0.11%
Iphone 13 Pro: 0.08%
Iphone 14: 0.88%
Iphone 14 Pro: 98.34%
Iphone 15: 0.04%
Iphone 15 Pro: 0.08%
Oppo Reno11 F: 0.03%
Samsung Galaxy M34: 0.05%
Samsung Galaxy S23: 0.00%
Samsung Galaxy S23 Ultra: 0.02%
Samsung Galaxy Z Fold5: 0.28%
Samsung Galaxy Z Fold6: 0.01%
Tcl Google Tv: 0.00%
Xiaomi Poco X6 Pro: 0.03%
Xiaomi Redmi Note 13: 0.04%
